# Site settings
title: Aditya Mandaleeka
description: "Aditya Mandaleeka"
first_name: "Aditya"
last_name: "Mandaleeka"
url: "http://mandaleeka.com/"
#baseurl: "/mandaleeka.com"
github_username: "adityamandaleeka"
twitter_username: "mandaleeka"
paginate: 5

# Build settings
markdown: kramdown
permalink: pretty

# Gems
gems: [jekyll-paginate]